### ISSUE TITLE
get error in running example for fluidex engine 

### ISSUE THREAD

**Issue by armagg** [fluidex/fluidex.js#2]
afeter runnig i get 
Caught error: TypeError: blake_hash_1.default is not a function
    at prv2bigint (/home/omid/dingir-exchange/examples/js/fluidex.js/src/eddsa.ts:17:20)
at Object.prv2pub (/home/omid/dingir-exchange/examples/js/fluidex.js/src/eddsa.ts:24:52)
    at new L2Account (/home/omid/dingir-exchange/examples/js/fluidex.js/src/account.ts:35:22)
    at Function.fromSignature (/home/omid/dingir-exchange/examples/js/fluidex.js/src/account.ts:102:21)
    at Function.fromPrivkey (/home/omid/dingir-exchange/examples/js/fluidex.js/src/account.ts:92:20)
    at Function.fromMnemonic (/home/omid/dingir-exchange/examples/js/fluidex.js/src/account.ts:86:20)
    at initAccounts (/home/omid/dingir-exchange/examples/js/trade.ts:34:23)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
npm ERR! code 1
npm ERR! path /home/omid/dingir-exchange/examples/js
npm ERR! command failed
npm ERR! command sh -c ts-node "trade.ts"

**Comment by 0xmountaintop** [comment]
can you provide more details? What did you run and how did you run it?
